name: snake_game
description: A classic Snake game for Flutter 2.10.5

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  provider: ^6.1.1
  screen_brightness: ^2.1.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


